src/objects/Product2.object
<CustomObject>
</CustomObject>

samples/src/objects/Product2.object
    <fields>
        <fullName>Maintenance_Cycle__c</fullName>
        <label>Maintenance Cycle</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>

src/objects/Work_Part__c.object
<CustomObject>
    <fields>
        <fullName>Equipment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Equipment</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Work Parts</relationshipLabel>
        <relationshipName>Work_Parts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Maintenance_Request__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Maintenance Request</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Work Parts</relationshipLabel>
        <relationshipName>Work_Parts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Work Part</label>
    <nameField>
        <label>Work Part Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Work Parts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/DB_WorkPartSelectorMock.cls
@isTest 
public class DB_WorkPartSelectorMock extends DB_WorkPartSelector{  
	Decimal daysTilNextServiceDue;
	
	public DB_WorkPartSelectorMock(Decimal daysTilNextServiceDue){
		this.daysTilNextServiceDue = daysTilNextServiceDue;
	}
	
    public override List<Work_Part__c> selectByMaintenanceRequestIdWithEquipment(Set<Id> idSet) {
    	Product2 equipmentTemplate = new Product2(maintenance_cycle__c = this.daysTilNextServiceDue);  
		Product2 equipment = TEST_EquipmentFactory.create(equipmentTemplate, TEST_DummyInsertModeEnum.MOCK);
		Work_Part__c workPartTemplate = new Work_Part__c(
			maintenance_request__c = new List<Id>(idSet)[0],
			equipment__c = equipment.id,
			equipment__r = equipment
		); 		
		return new List<Work_Part__c>{ TEST_WorkPartFactory.create(workPartTemplate, TEST_DummyInsertModeEnum.MOCK)};  
    }  
	
}