src/objects/Work_Part__c.object
<CustomObject>
    <fields>
        <fullName>Equipment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Equipment</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Work Parts</relationshipLabel>
        <relationshipName>Work_Parts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Maintenance_Request__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Maintenance Request</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Work Parts</relationshipLabel>
        <relationshipName>Work_Parts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Work Part</label>
    <nameField>
        <label>Work Part Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Work Parts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/DB_WorkPartSelector.cls
public virtual class DB_WorkPartSelector extends fflib_SObjectSelector {

    public List<Schema.SObjectField> getSObjectFieldList() {
        return new List<Schema.SObjectField>{
                Work_Part__c.id,
                Work_Part__c.equipment__c,
                Work_Part__c.maintenance_request__c
        };
    }

    public Schema.SObjectType getSObjectType() {
        return Work_Part__c.sObjectType;
    }
    
    public virtual List<Work_Part__c> selectByMaintenanceRequestIdWithEquipment(Set<Id> idSet) {
        fflib_QueryFactory queryFactory = newQueryFactory();
        new DB_EquipmentSelector().configureQueryFactoryFields(queryFactory, 'equipment__c');
        return (List<Work_Part__c>) Database.query(
                queryFactory.setCondition('maintenance_request__c IN :idSet').toSOQL()
        );
    }  
}